### ISSUE TITLE
Incorrect interpretation of special characters

### ISSUE THREAD

**Issue by melissis** [jobiewong/espanso-emojis#2]
For example:
`Japanese “here” button` has been turned into `:japanese__here__button:` (double underscores)
and `Congo - Kinshasa` has been turned into `:congo___kinshasa:` (triple underscore).

**Comment by melissis** [comment]
Another issue: `Côte d’Ivoire` to `c�te divoire`.
Search for "�" and you'll find some more; "pi�ata".

**Comment by jobiewong** [comment]
Now fixed in v1.3
